version: 2
workflows:
  version: 2
  test:
    jobs:
      - latest-1
      - latest
jobs:
  latest-1:
    docker:
      - image: "circleci/golang:1.15"
    steps: &ref_0
      - checkout
      - restore_cache:
          keys:
            - go-mod-{{ checksum "go.sum" }}
      - run: go test -v ./...
      - run: go install ./...
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
  latest:
    docker:
      - image: "circleci/golang:1.16"
    steps: *ref_0
